#cloud-config
write_files:
  - owner: root:root
  - path: /cloud-init-data.txt
    content: |
      ${cloud-init-data}
runcmd:
  - set -x
  - . /cloud-init-data.txt
  - git clone http://github.com/stujfiter/kubernetes.git
  - (cd /kubernetes; git checkout connectToStorage)
  - /kubernetes/azure/install_azure_cli.sh
  - /kubernetes/install-kubeadm-ubuntu.sh
  - if [ "$isMaster" = "true" ]; then /kubernetes/start-master.sh; fi
  - if [ "$isMaster" = "true" ]; then /kubernetes/azure/store-token.sh; fi
  # - kubelet
  # - export NODE_NAME=$(hostname)
  # - export NODE_IP=$(ifconfig eth0 | grep Mask | awk '{print $2}'| cut -f2 -d:)
  # - export DISCOVERY_TOKEN=$(cat cloud-init-data.txt)
  # - sed "s/\${NODE_NAME}/${NODE_NAME}/g" /kubernetes/etcd.yaml | sed "s%\${NODE_IP}%${NODE_IP}%g" | sed "s/\${DISCOVERY_TOKEN}/${DISCOVERY_TOKEN}/g" | tee /etc/kubernetes/manifests/etcd.yaml
